// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/luohaocode/Go-000/Week04/ent"
	"github.com/luohaocode/Go-000/Week04/internal/biz"
	"github.com/luohaocode/Go-000/Week04/internal/data"
	"github.com/luohaocode/Go-000/Week04/internal/service"
)

// Injectors from wire.go:

func InitializeService(client *ent.Client) (*service.RecordUserService, error) {
	recordRepo := data.NewUserRepo()
	recordUseCase := biz.NewRecordUserCase(recordRepo)
	recordUserService := service.NewRecordUserService(client, recordUseCase)
	return recordUserService, nil
}
